/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package papyrusdatabase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Mostafa Hassan
 */
public class AddSupplier extends javax.swing.JFrame {

    private Connection con;
    private Statement st;
    private ResultSet rs;
    boolean done = true;

    /**
     * Creates new form AddSupplier
     */
    public AddSupplier() {
        initComponents();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/shop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "signmein");

            st = con.createStatement();
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }

    public void InsertData(String name, String date, int amount, int total) {

        try {
            String sql = "INSERT INTO supplier (name,Date,Amount,TotalSales) VALUES ('" + name + "','" + date + "'," + amount + "," + total + ")";
            st.executeUpdate(sql);
            done = true;
        } catch (Exception e) {
            System.out.println(e);
            done = false;
        }
    }

    String name, date;
    int amount, total;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonBack = new javax.swing.JButton();
        TotalA = new javax.swing.JTextField();
        sd = new javax.swing.JLabel();
        AmountA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DateA = new javax.swing.JTextField();
        NameA = new javax.swing.JTextField();
        asd = new javax.swing.JLabel();
        ss = new javax.swing.JLabel();
        Load = new javax.swing.JLabel();
        Save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ButtonBack.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        ButtonBack.setText("Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        sd.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        sd.setText("Total Sales");

        AmountA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountAActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        jLabel3.setText("Amount");

        DateA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateAActionPerformed(evt);
            }
        });

        asd.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        asd.setText("Name");

        ss.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        ss.setText("Date");

        Load.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        Load.setText("Loading");

        Save.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(553, 553, 553)
                .addComponent(Save, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addGap(279, 279, 279)
                .addComponent(Load)
                .addGap(101, 101, 101))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(456, 456, 456)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(ss)
                        .addComponent(sd)
                        .addComponent(asd))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DateA)
                        .addComponent(AmountA)
                        .addComponent(TotalA)
                        .addComponent(NameA, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGap(456, 456, 456)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Save))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                        .addComponent(Load)))
                .addGap(55, 55, 55))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NameA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(asd))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ss)
                        .addComponent(DateA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(AmountA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TotalA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sd))
                    .addContainerGap(183, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        AddSupplier.this.setVisible(false);
        new Supplier().setVisible(true);
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void AmountAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountAActionPerformed

    private void DateAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateAActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        name = NameA.getText().trim();
        date = DateA.getText().trim();
        try {
            amount = Integer.parseInt(AmountA.getText().trim());
        } catch (Exception e) {
            amount=0;
            done=false;
        }
        try {

            total = Integer.parseInt(TotalA.getText().trim());
        } catch (Exception e) {
            total=0;
            done=false;
        }
        
        if (amount == 0) {
            JOptionPane.showMessageDialog(new AddSupplier(), "False Amount !");
        }
        if (total == 0) {
            JOptionPane.showMessageDialog(new AddSupplier(), "False Total Sales !");
        } else if (done) {
            InsertData(name, date, amount, total);
            Load.setText("Successfully Saved");
            NameA.setText("");
            DateA.setText("");
            AmountA.setText("");
            TotalA.setText("");
        } else {
            Load.setText("Failed !");
        }
        done=true;
        

    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountA;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JTextField DateA;
    private javax.swing.JLabel Load;
    private javax.swing.JTextField NameA;
    private javax.swing.JButton Save;
    private javax.swing.JTextField TotalA;
    private javax.swing.JLabel asd;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel sd;
    private javax.swing.JLabel ss;
    // End of variables declaration//GEN-END:variables
}
