/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package papyrusdatabase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Mostafa Hassan
 */
public class ReceiveStore extends javax.swing.JFrame {

    private Connection con;
    private Statement st;
    private ResultSet rs;

    /**
     * Creates new form ReceiveStore
     */
    public ReceiveStore() {
        initComponents();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/shop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "");

            st = con.createStatement();
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }

    public String Getdata(int modelno) {
        String d = "", query = "";
        int modelnum = 0, c = 0;

        query = "SELECT * FROM picture ";
        try{
        rs = st.executeQuery(query);
        while (rs.next()) {
                c++;
                String Name = rs.getString("name");
                int Amount = rs.getInt("amount");
                String size = rs.getString("size");
                String Supplier = rs.getString("Supplier");
                if (Name.length() >= 8 && Name.length() < 20) {
                    d += c + ")" + "\t\t" + Name + "\t\t\t" + Amount + "\t\t\t" + size + "\t\t\t\t" + Supplier + "";
                    d += "\n";
                    d += "\n";
                } else {
                    d += c + ")" + "\t\t" + Name + "\t\t\t\t\t" + Amount + "\t\t\t" + size + "\t\t\t\t" + Supplier + "";
                    d += "\n";
                    d += "\n";
                }
            }
        }catch(Exception e){}
        
        return d;

    }
    
     String done;
     int amount,modelnumber=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonBack = new javax.swing.JButton();
        RecieveData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Show = new javax.swing.JTextArea();
        modelno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Load = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ButtonBack.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        ButtonBack.setText("Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        RecieveData.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        RecieveData.setText("Receive");
        RecieveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecieveDataActionPerformed(evt);
            }
        });

        Show.setColumns(20);
        Show.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        Show.setRows(5);
        jScrollPane1.setViewportView(Show);

        modelno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelnoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        jLabel5.setText("enter the ModelNo.");

        Load.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        Load.setText("Loading");

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        jLabel1.setText("Name");

        jLabel4.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        jLabel4.setText("size");

        jLabel3.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        jLabel3.setText("amount");

        jLabel2.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        jLabel2.setText("supplier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonBack))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(modelno, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(RecieveData, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(Load)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(225, 225, 225)
                .addComponent(jLabel4)
                .addGap(240, 240, 240)
                .addComponent(jLabel2)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonBack)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecieveData, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Load))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        ReceiveStore.this.setVisible(false);
        new store().setVisible(true);
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void RecieveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecieveDataActionPerformed
        
        done = Getdata(modelnumber);
        Show.setText(done);
        

    }//GEN-LAST:event_RecieveDataActionPerformed

    private void modelnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiveStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiveStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiveStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiveStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiveStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JLabel Load;
    private javax.swing.JButton RecieveData;
    private javax.swing.JTextArea Show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField modelno;
    // End of variables declaration//GEN-END:variables
}
