/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package papyrusdatabase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Mustafa
 */
public class ReceiveSales extends javax.swing.JFrame {

    private Connection con;
    private Statement st;
    private ResultSet rs;
    boolean done = false,CnExist=false;

    /**
     * Creates new form ReceiveSales
     */
    public ReceiveSales() {
        initComponents();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/shop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "signmein");

            st = con.createStatement();
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }

    public String getData(String Cn) {

        String d = "", N, No = "", query,Cname="";
        int c = 0;
        try {
            if (Cn.equals("")) {
                query = "SELECT * FROM sales ";
            } else {
                query = "SELECT * FROM sales WHERE CompanyName = '" + Cn + "' ";
            }
            rs = st.executeQuery(query);
            while (rs.next()) {
                c++;
                String Gname = rs.getString("GuideName");
                 Cname = rs.getString("CompanyName");
                String total = rs.getString("TotalSales");
                String Ccom = rs.getString("CompanyCommission");
                N = rs.getString("Notes");
                if (Gname.length() >= 5 && Gname.length() < 15) {
                    d += c + ") " + Gname + "\t\t\t\t" + Cname + "\t\t\t\t\t" + total + "\t\t\t\t" + Ccom + "";
                    d += "\n";
                    d += "\n";
                }  else if(Gname.length() < 5) {
                    d += c + ") " + Gname + "\t\t\t\t\t" + Cname + "\t\t\t\t\t" + total + "\t\t\t\t" + Ccom + "";
                    d += "\n";
                    d += "\n";
                }else {
                    d += c + ") " + Gname + "\t\t\t" + Cname + "\t\t\t\t\t" + total + "\t\t\t\t" + Ccom + "";
                    d += "\n";
                    d += "\n";
                }
                No += c + ") " + N;
                No += "\n";
                No += "\n";
            }
            if(!Cname.equals("")){
                CnExist=true;
            }
            NotesShow.setText(No);
            done = true;
        } catch (Exception e) {
            System.out.println(e);
            done = false;
        }

        return d;
    }

    String Data = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Load = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DateA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Show = new javax.swing.JTextArea();
        Load1 = new javax.swing.JLabel();
        Load2 = new javax.swing.JLabel();
        Load3 = new javax.swing.JLabel();
        Load4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        NotesShow = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ButtonBack.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        ButtonBack.setText("Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jButton1.setText("Receive");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Load.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        Load.setText("Loading");

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        jLabel1.setText("Enter the Company");

        Show.setColumns(20);
        Show.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        Show.setRows(5);
        jScrollPane1.setViewportView(Show);

        Load1.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        Load1.setText("Guide");

        Load2.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        Load2.setText("Total");

        Load3.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        Load3.setText("Company");

        Load4.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        Load4.setText("Company Commission");

        jLabel2.setFont(new java.awt.Font("Courier New", 3, 16)); // NOI18N
        jLabel2.setText("Notes");

        NotesShow.setColumns(20);
        NotesShow.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        NotesShow.setRows(5);
        jScrollPane2.setViewportView(NotesShow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(Load1)
                                .addGap(309, 309, 309)
                                .addComponent(Load3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Load2)
                                .addGap(180, 180, 180)
                                .addComponent(Load4)
                                .addGap(68, 68, 68)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonBack)
                                .addGap(192, 192, 192)))
                        .addGap(39, 39, 39)
                        .addComponent(DateA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Load)
                        .addGap(237, 237, 237))))
            .addGroup(layout.createSequentialGroup()
                .addGap(551, 551, 551)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Load)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DateA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Load1)
                    .addComponent(Load2)
                    .addComponent(Load3)
                    .addComponent(Load4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        ReceiveSales.this.setVisible(false);
        new Sales().setVisible(true);
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Data = getData(DateA.getText());
        Show.setText(Data);
        if (CnExist == false){
            JOptionPane.showMessageDialog(new ReceiveSales(), "no company with this name found !");
        }

        if (done) {
            Load.setText("Success");
        } else {
            Load.setText("Failed");
        }
        CnExist = false;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiveSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiveSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiveSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiveSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiveSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JTextField DateA;
    private javax.swing.JLabel Load;
    private javax.swing.JLabel Load1;
    private javax.swing.JLabel Load2;
    private javax.swing.JLabel Load3;
    private javax.swing.JLabel Load4;
    private javax.swing.JTextArea NotesShow;
    private javax.swing.JTextArea Show;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
